# config.yaml

ports:
  - 10001
  - 10002
  - 10003
  - 10004
  - 10005
  - 10006
  - 10007
  - 10008
  - 10009
  - 10010

# 프록시당 최소 대기 시간 (초)
min_delay: 10

# 요청 실패 시 최대 재시도 횟수
max_retries: 2

worker_count: 1
rate_limit_per_min: 60    # slowapi 전역

cors_origins:
  - "http://13.209.194.237:3000" # AWS
  - "13.209.194.237:3000"  # AWS
  - "http://localhost:3000"      # Next.js dev
  - "http://127.0.0.1:3000"